import "./globals.css";
import type { Metadata } from "next";
import RootComponet from "@/components/Wrapper";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TimeCraft",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RootComponet>{children}</RootComponet>
        <Toaster />
      </body>
    </html>
  );
}
